name: SonarCloud Analysis
on:
  workflow_dispatch:
  pull_request:
    branches: 
      -develop
  push:
    branches:
      -master
    
jobs:
  sonarcloud:
    name: Build
    runs-on: ubuntu-latest
    
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
