name: CI

on:
  workflow_call:

jobs:
  ci:
    name: CI
    runs-on: [self-hosted, dotnet6]
    steps:
      -name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
buckley/Setup-MSBuild@1176db82e64cd53b4944f0e57c2abec104b4782d
  uses: warrenbuckley/Setup-MSBuild@v1
          
       
      
      
