name: PR Validation
on:
  workflow_dispatch:

  pull_request:
    branches: [develop, master]
  push:
    branches: [develop]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit
